### ISSUE TITLE
Keep question preview building same color

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/umbrella_city#32]
When you click on the building the preview image with the question should be exactly the same as the current piece state (always grey)   Currently it shows the best (colored) piece

From:  #21

> Tom Says: Hey Guys, 
> When a grey building is clicked on from the map view, the piece that is shown in the circle should exactly reflect the image that was clicked on. At the moment all the images in the question circle icon are the perfect solution regardless of the state of the original building.

Thanks :)

**Comment by formerhermit** [comment]
This still seems to be an issue? And one block now has a mismatched game piece
![1](https://cloud.githubusercontent.com/assets/18323317/15037994/e8aee046-1297-11e6-86a1-2de9d1dfee0b.PNG)
![2](https://cloud.githubusercontent.com/assets/18323317/15037995/e8b4e0ea-1297-11e6-95f7-9e207d73a5ab.PNG)

**Comment by RiteshTC** [comment]
Should be fixed now, the error was introduced because of resetting the sequence number to 1

**Comment by formerhermit** [comment]
Hi @RiteshAppirio We are still seeing the partially coloured game piece 
![capture](https://cloud.githubusercontent.com/assets/18323317/15066383/90e1e876-1360-11e6-98bb-3be7dac3ff9e.PNG)
We should be seeing the grey version of this building?
![b](https://cloud.githubusercontent.com/assets/18323317/15066431/f57b8c10-1360-11e6-9bbc-2d4276b2cadb.PNG)

**Comment by RiteshTC** [comment]
Should be fixed now. Steve has supplied separate images for each block

**Comment by formerhermit** [comment]
This is fixed, thanks!
